name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build Docker image
      run: docker build -t playwright-pet .
    - name: Run tests in Docker
      run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results playwright-pet
    - name: Generate Allure Report
      run: allure generate ${{ github.workspace }}/allure-results -o ${{ github.workspace }}/allure-report
    # - name: Generate Allure Report
      # run: docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -v ${{ github.workspace }}/allure-report:/app/allure-report allure-framework/allure-cli:latest generate /app/allure-results -o /app/allure-report
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
    # - name: Run tests in Docker
    #   run: docker run --rm -v ${{ github.workspace }}/playwright-report:/app/playwright-report playwright-pet
    # - name: Upload Playwright Report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: playwright-report
    #     path: playwright-report/