name: PW image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'A set of tests to run'
        required: true
        default: '@regression'
      exclude_tag:
        description: 'A set of tests to exclude'
        required: false
        default: ''
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Start Playwright container with long-running process
      run: docker run -d --name pw-pet -v ${{ github.workspace }}:/app -w /app mcr.microsoft.com/playwright:v1.49.1-noble tail -f /dev/null
    - name: Install dependencies
      run: |
        docker exec pw-pet apt-get update && apt-get install -y \
          fonts-liberation \
          fonts-noto \
          fonts-noto-cjk \
          fonts-noto-color-emoji \
          fonts-noto-mono \
          fonts-noto-unhinted \
          fonts-dejavu \
          fonts-freefont-ttf \
          fonts-roboto \
          fonts-droid-fallback \
          fonts-ubuntu \
          fonts-ipafont-gothic \
          fonts-ipafont-mincho \
          fonts-unfonts-core \
          fonts-arphic-uming \
          fonts-arphic-ukai \
          --no-install-recommends && \
          rm -rf /var/lib/apt/lists/*
        docker exec pw-pet npm install
        docker exec pw-pet npx playwright install chrome --with-deps
    - name: Run tests in Docker
      run: |
        if [ -n "${{ inputs.exclude_tag }}" ]; then
          docker exec pw-pet npx playwright test --grep="${{ inputs.tag }}" --grep-invert="${{ inputs.exclude_tag }}"
        else
          docker exec pw-pet npx playwright test --grep="${{ inputs.tag }}"
        fi
      continue-on-error: true
    - name: Copy snapshots to a single directory inside the container
      run: docker exec pw-pet sh -c 'mkdir -p /app/all-snapshots && cp -r /app/tests/*snapshots /app/all-snapshots'
      continue-on-error: true
    - name: Create directories for reports and screenshots
      run: |
        sudo chmod -R 777 ./playwright-report
        sudo chmod -R 777 ./screenshots
    - name: Copy Playwright Screenshots from Docker container
      run: sudo docker cp pw-pet:/app/all-snapshots ./screenshots
      continue-on-error: true
    - name: Copy Playwright Report from Docker container
      run: sudo docker cp pw-pet:/app/playwright-report ./playwright-report
      continue-on-error: true
    - name: Upload Playwright Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: ./screenshots
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
    - name: Cleanup
      run: docker rm -f pw-pet